"""activate status

Revision ID: 0ce6bb23753e
Revises: e096793a063c
Create Date: 2023-02-20 10:38:36.368848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce6bb23753e'
down_revision = 'e096793a063c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('active_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'active_status')
    # ### end Alembic commands ###
