"""busy room status

Revision ID: 7d40aa6d2e6c
Revises: 45bf06cd6198
Create Date: 2023-02-20 12:14:18.696854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d40aa6d2e6c'
down_revision = '45bf06cd6198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('busy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'busy')
    # ### end Alembic commands ###
